name: ApiOverview
version: '${version}'
main: de.otto.minecrafttutorium.MinecraftTutorium
api-version: 1.17
commands:
  heal:
    description: Heals the Player by the amount given
    usage: /heal
  boom:
    description: Makes an explosion
    usage: /boom